### ISSUE TITLE
Error while "Executing model transformation"

### ISSUE THREAD

**Issue by adnanimeri** [AToMPM/atompm#79] opened 2020-06-09 15:29 UTC
While attempting to execute model transformation, an error is generation as follows:

"ERROR :: failed to choose next rule :: Traceback (most recent call last):
C:\  ... \ATOM PM\atompm-portable\atompm\mt\ptcal\ptcal.py", line 1044, in _step
    nr = self._nextRule()

C:\  ... \ ATOM PM\atompm-portable\atompm\mt\ptcal\ptcal.py", line 444, in _nextRule
    ns = mtc.nextStep()

C:\  ...\ATOM PM\atompm-portable\atompm\mt\ptcal\motifcontext.py", line 330, in nextStep
    timeNextStep = clock()
NameError: name 'clock' is not defined

I am using Python 3.8.

**Comment by BentleyJOakes** [comment] 2020-06-09 20:36
Thanks for the report.

Apologies for the error, it is caused by a deprecated function in Python3.8. It should be fixed by https://github.com/AToMPM/atompm/commit/bfddd0b2046aa99244668db2cf7d5e70c7f8b94f.

I will make a new release and portable version as soon as possible (within the next day or two).

**Closed by BentleyJOakes** 2020-06-09 20:36 UTC
